export const NewsActionTypes = {
    START_NEWS_FETCHING: "news/START_NEWS_FETCHING",
    FINISHED_NEWS_FETCHING: "news/FINISHED_NEWS_FETCHING",
    CHANGE_SEARCH_Q: "news/CHANGE_SEARCH_Q",
    RESET_SEARCH: "news/RESET_SEARCH",
    CHANGE_CATEGORY: "news/CHANGE_CATEGORY"
}